import turtle

def triangle(length):
    turtle.penup()
    turtle.goto(-100,-100)
    turtle.pendown()
    turtle.fillcolor("blue")
    turtle.begin_fill()
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.end_fill()
    turtle.penup()

    turtle.forward(length)
    turtle.pendown()
    turtle.fillcolor("green")
    turtle.begin_fill()
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.end_fill()
    turtle.penup()

    turtle.goto(-100,-100)
    turtle.left(90)
    turtle.forward(length)
    turtle.right(90)
    turtle.pendown()
    turtle.fillcolor("red")
    turtle.begin_fill()
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.end_fill()
    turtle.penup()

    turtle.forward(length)
    turtle.pendown()
    turtle.fillcolor("orange")
    turtle.begin_fill()
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.end_fill()
    turtle.penup()


def main():
    triangle(100)
    input()

if __name__ == "__main__":
    main()